# Generated by Django 5.2.4 on 2025-08-03 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_category_contact_newsletter_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='anime_title_jp',
            field=models.CharField(blank=True, help_text='Japanese title', max_length=255, verbose_name='Japanese Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='anime_type',
            field=models.CharField(blank=True, choices=[('tv', 'TV Series'), ('movie', 'Movie'), ('ova', 'OVA'), ('special', 'Special'), ('ona', 'ONA')], max_length=10, verbose_name='Anime Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='episode_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Episode Count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(help_text='Brief description for preview', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Release Year'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
